version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: SQL-HDI
    environment:
      MYSQL_ROOT_PASSWORD: hdi
      MYSQL_DATABASE: HDI
      MYSQL_USER: hdi12345678
      MYSQL_PASSWORD: hdi12345678
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: